// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvVrpJGarFD6uqr0em-OlF9qif-UiLXdk',
    appId: '1:805846412469:web:38e5dcc4e3559dfab4e2fc',
    messagingSenderId: '805846412469',
    projectId: 'gimmethat-7f8cb',
    authDomain: 'gimmethat-7f8cb.firebaseapp.com',
    storageBucket: 'gimmethat-7f8cb.firebasestorage.app',
    measurementId: 'G-Y9VPJ8SL4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMRvkywIuW2CEzAY6fOH1BJ4qNUd8VSgI',
    appId: '1:805846412469:android:2a00a7aa5ee22660b4e2fc',
    messagingSenderId: '805846412469',
    projectId: 'gimmethat-7f8cb',
    storageBucket: 'gimmethat-7f8cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeN3CArJxJ3VjYDegIxtn39vFYFOmcK7s',
    appId: '1:805846412469:ios:7929be2a2aae96fab4e2fc',
    messagingSenderId: '805846412469',
    projectId: 'gimmethat-7f8cb',
    storageBucket: 'gimmethat-7f8cb.firebasestorage.app',
    iosBundleId: 'com.example.gimmethat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeN3CArJxJ3VjYDegIxtn39vFYFOmcK7s',
    appId: '1:805846412469:ios:7929be2a2aae96fab4e2fc',
    messagingSenderId: '805846412469',
    projectId: 'gimmethat-7f8cb',
    storageBucket: 'gimmethat-7f8cb.firebasestorage.app',
    iosBundleId: 'com.example.gimmethat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvVrpJGarFD6uqr0em-OlF9qif-UiLXdk',
    appId: '1:805846412469:web:576255517d295ff7b4e2fc',
    messagingSenderId: '805846412469',
    projectId: 'gimmethat-7f8cb',
    authDomain: 'gimmethat-7f8cb.firebaseapp.com',
    storageBucket: 'gimmethat-7f8cb.firebasestorage.app',
    measurementId: 'G-P1YMVP061S',
  );
}
